[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Kumar Akshat <55215422+iaxat@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
